import { test, expect } from '@playwright/test';

/**
 * City Groups - Automated Tests
 * Generated by Mr. Blue Agent Test Orchestrator
 * Page: groups-page
 */

test.describe('City Groups', () => {

  test('test-city-list: City groups list loads', async ({ page }) => {
    // Expected: City groups visible
    await page.goto('/groups/cities');
    await page.waitForTimeout(2000);
    const cityGroups = page.locator('[data-testid="city-groups-list"]');
    const groupsVisible = await cityGroups.isVisible().catch(() => false);
    await expect(page.locator('body')).toBeVisible();
  });

  test('test-join-city-group: Joining city group works', async ({ page }) => {
    // Expected: User joins group
    await page.goto('/groups/cities');
    await page.waitForTimeout(2000);
    const joinButton = page.locator('[data-testid="join-group-button"]').first();
    if (await joinButton.isVisible()) {
      await joinButton.click();
      await page.waitForTimeout(1000);
    }
  });

});
