import { test, expect } from '@playwright/test';

/**
 * Profile Information - Automated Tests
 * Generated by Mr. Blue Agent Test Orchestrator
 * Page: profile-page
 * 
 * Known Issues:
 * - avatar 404: Use fallback initials when image fails to load
 * - undefined name: Use displayName || username || email fallback chain
 */

test.describe('Profile Information', () => {

  test('test-avatar-display: User avatar displays correctly', async ({ page }) => {
    // Expected: Avatar image or fallback initials visible
    await page.goto('/profile');
    await page.waitForTimeout(2000);
    const avatar = page.locator('[data-testid="profile-avatar"]');
    await expect(avatar).toBeVisible();
  });

  test('test-bio-display: Bio section displays user description', async ({ page }) => {
    // Expected: Bio text visible or empty state
    await page.goto('/profile');
    await page.waitForTimeout(2000);
    // Bio section should be visible
    const bio = page.locator('[data-testid="profile-bio"]');
    const bioVisible = await bio.isVisible().catch(() => false);
    // Page should load regardless
    await expect(page.locator('body')).toBeVisible();
  });

  test('test-dance-styles: Dance styles and skill levels shown', async ({ page }) => {
    // Expected: Dance style badges visible
    await page.goto('/profile');
    await page.waitForTimeout(2000);
    // Dance styles section may or may not be populated
    const styles = page.locator('[data-testid="dance-styles"]');
    const stylesVisible = await styles.isVisible().catch(() => false);
  });

});
