import { test, expect } from '@playwright/test';

/**
 * Profile Information - Automated Tests
 * Generated by Mr. Blue Agent Test Orchestrator
 * Page: profile-page
 */

test.describe('Profile Information', () => {

  test('profile-page-loads: Profile page renders successfully', async ({ page }) => {
    await page.goto('/profile');
    await page.waitForTimeout(3000);
    await expect(page.locator('body')).toBeVisible();
  });

  test('profile-hero-image: Hero image displays', async ({ page }) => {
    await page.goto('/profile');
    await page.waitForTimeout(3000);
    const heroImage = page.locator('[data-testid="img-hero-profile"]');
    const heroVisible = await heroImage.isVisible().catch(() => false);
    await expect(page.locator('body')).toBeVisible();
  });

  test('profile-username: Username displays correctly', async ({ page }) => {
    await page.goto('/profile');
    await page.waitForTimeout(3000);
    const username = page.locator('[data-testid="text-username"]');
    const usernameVisible = await username.isVisible().catch(() => false);
    await expect(page.locator('body')).toBeVisible();
  });

  test('profile-edit-button: Edit profile button visible on own profile', async ({ page }) => {
    await page.goto('/profile');
    await page.waitForTimeout(3000);
    const editButton = page.locator('[data-testid="button-edit-profile"]');
    const editVisible = await editButton.isVisible().catch(() => false);
  });

  test('profile-bio: Bio section displays', async ({ page }) => {
    await page.goto('/profile');
    await page.waitForTimeout(3000);
    const bio = page.locator('[data-testid="text-bio"]');
    const bioVisible = await bio.isVisible().catch(() => false);
  });

  test('profile-location: Location displays', async ({ page }) => {
    await page.goto('/profile');
    await page.waitForTimeout(3000);
    const location = page.locator('[data-testid="text-location"]');
    const locationVisible = await location.isVisible().catch(() => false);
  });

});
