import { test, expect } from '@playwright/test';
import { testUsers, loginAsTestUser, setupAuthenticatedSession } from './helpers/test-auth';

/**
 * Comprehensive Platform Test Suite
 * Generated by Mr. Blue Agent Test Orchestrator
 * 
 * Tests all major platform features across all pages
 * Uses test users to verify authenticated functionality
 */

test.describe('Comprehensive Platform Tests', () => {
  
  test.describe('Public Pages', () => {
    
    test('Landing page loads correctly', async ({ page }) => {
      await page.goto('/');
      await page.waitForTimeout(2000);
      await expect(page).toHaveTitle(/Mundo Tango|Tango/i);
      await expect(page.locator('body')).toBeVisible();
    });

    test('Login page accessible', async ({ page }) => {
      await page.goto('/login');
      await page.waitForTimeout(1000);
      const loginForm = page.locator('form, [data-testid="login-form"]');
      const formVisible = await loginForm.isVisible().catch(() => false);
      await expect(page.locator('body')).toBeVisible();
    });

    test('Register page accessible', async ({ page }) => {
      await page.goto('/register');
      await page.waitForTimeout(1000);
      await expect(page.locator('body')).toBeVisible();
    });

  });

  test.describe('Feed Page Features', () => {

    test('Feed loads with content', async ({ page }) => {
      await page.goto('/feed');
      await page.waitForTimeout(3000);
      const feedContainer = page.locator('[data-testid="feed-container"]');
      const feedVisible = await feedContainer.isVisible().catch(() => false);
      await expect(page.locator('body')).toBeVisible();
    });

    test('Post creation UI visible', async ({ page }) => {
      await page.goto('/feed');
      await page.waitForTimeout(2000);
      const createButton = page.locator('[data-testid="create-post-button"]');
      const buttonVisible = await createButton.isVisible().catch(() => false);
      // Button may require auth
    });

    test('Infinite scroll triggers', async ({ page }) => {
      await page.goto('/feed');
      await page.waitForTimeout(2000);
      await page.evaluate(() => window.scrollTo(0, document.body.scrollHeight));
      await page.waitForTimeout(2000);
      await expect(page.locator('body')).toBeVisible();
    });

  });

  test.describe('Profile Page Features', () => {

    test('Profile page loads', async ({ page }) => {
      await page.goto('/profile');
      await page.waitForTimeout(2000);
      await expect(page.locator('body')).toBeVisible();
    });

    test('Profile avatar displays', async ({ page }) => {
      await page.goto('/profile');
      await page.waitForTimeout(2000);
      const avatar = page.locator('[data-testid="profile-avatar"]');
      const avatarVisible = await avatar.isVisible().catch(() => false);
    });

  });

  test.describe('Events Page Features', () => {

    test('Events calendar loads', async ({ page }) => {
      await page.goto('/events/calendar');
      await page.waitForTimeout(2000);
      await expect(page.locator('body')).toBeVisible();
    });

    test('Events list page loads', async ({ page }) => {
      await page.goto('/events');
      await page.waitForTimeout(2000);
      await expect(page.locator('body')).toBeVisible();
    });

  });

  test.describe('Messages Page Features', () => {

    test('Messages page loads', async ({ page }) => {
      await page.goto('/messages');
      await page.waitForTimeout(2000);
      await expect(page.locator('body')).toBeVisible();
    });

  });

  test.describe('Housing Page Features', () => {

    test('Housing search loads', async ({ page }) => {
      await page.goto('/housing');
      await page.waitForTimeout(2000);
      await expect(page.locator('body')).toBeVisible();
    });

  });

  test.describe('Groups Page Features', () => {

    test('Groups page loads', async ({ page }) => {
      await page.goto('/groups');
      await page.waitForTimeout(2000);
      await expect(page.locator('body')).toBeVisible();
    });

  });

  test.describe('Financial Page Features', () => {

    test('Financial dashboard loads', async ({ page }) => {
      await page.goto('/financial');
      await page.waitForTimeout(2000);
      await expect(page.locator('body')).toBeVisible();
    });

  });

  test.describe('Mr. Blue AI Features', () => {

    test('Mr. Blue chat loads', async ({ page }) => {
      await page.goto('/mrblue');
      await page.waitForTimeout(2000);
      await expect(page.locator('body')).toBeVisible();
    });

    test('VibeCoding interface loads', async ({ page }) => {
      await page.goto('/mrblue/vibecoding');
      await page.waitForTimeout(2000);
      await expect(page.locator('body')).toBeVisible();
    });

  });

  test.describe('Admin Pages (Require Auth)', () => {

    test('Admin dashboard redirects or loads', async ({ page }) => {
      await page.goto('/admin');
      await page.waitForTimeout(2000);
      // May redirect to login if not authenticated
      await expect(page.locator('body')).toBeVisible();
    });

  });

  test.describe('API Health Checks', () => {

    test('Agent ecosystem health API works', async ({ page }) => {
      const response = await page.request.get('/api/mrblue/qa/ecosystem-health');
      expect(response.status()).toBe(200);
      const data = await response.json();
      expect(data.success).toBe(true);
      expect(data.data.totalPageAgents).toBeGreaterThan(0);
    });

    test('Testable features API works', async ({ page }) => {
      const response = await page.request.get('/api/mrblue/qa/testable-features');
      expect(response.status()).toBe(200);
      const data = await response.json();
      expect(data.success).toBe(true);
      expect(Array.isArray(data.data)).toBe(true);
    });

  });

});
