import { test, expect } from '@playwright/test';

/**
 * Housing Listing Search - Automated Tests
 * Generated by Mr. Blue Agent Test Orchestrator
 * Page: housing-page
 * 
 * Known Issues:
 * - geocoding fail: Show error message and suggest manual coordinate entry
 */

test.describe('Housing Listing Search', () => {

  test('test-search-page: Search page loads', async ({ page }) => {
    // Expected: Search form and results visible
    await page.goto('/housing');
    await page.waitForTimeout(2000);
    const search = page.locator('[data-testid="housing-search"]');
    const searchVisible = await search.isVisible().catch(() => false);
    await expect(page.locator('body')).toBeVisible();
  });

  test('test-location-filter: Location filter works', async ({ page }) => {
    // Expected: Results filtered by location
    await page.goto('/housing');
    await page.waitForTimeout(2000);
    const locationInput = page.locator('[data-testid="location-input"]');
    if (await locationInput.isVisible()) {
      await locationInput.fill('Buenos Aires');
      const searchButton = page.locator('[data-testid="search-button"]');
      if (await searchButton.isVisible()) {
        await searchButton.click();
        await page.waitForTimeout(2000);
      }
    }
  });

  test('test-date-filter: Date range filter works', async ({ page }) => {
    // Expected: Results filtered by dates
    await page.goto('/housing');
    await page.waitForTimeout(2000);
    const datePicker = page.locator('[data-testid="date-picker"]');
    if (await datePicker.isVisible()) {
      await datePicker.click();
      await page.waitForTimeout(1000);
    }
  });

});
