import { test, expect } from '@playwright/test';

/**
 * Housing Listing Search - Automated Tests
 * Generated by Mr. Blue Agent Test Orchestrator
 * Page: housing-page
 */

test.describe('Housing Search Page', () => {

  test('housing-search-page-loads: Search page loads', async ({ page }) => {
    await page.goto('/housing/search');
    await page.waitForTimeout(3000);
    await expect(page.locator('body')).toBeVisible();
  });

  test('housing-search-heading: Search heading visible', async ({ page }) => {
    await page.goto('/housing/search');
    await page.waitForTimeout(3000);
    const heading = page.locator('[data-testid="heading-housing-search"]');
    const headingVisible = await heading.isVisible().catch(() => false);
  });

  test('housing-city-input: City input visible', async ({ page }) => {
    await page.goto('/housing/search');
    await page.waitForTimeout(3000);
    const cityInput = page.locator('[data-testid="input-city"]');
    const inputVisible = await cityInput.isVisible().catch(() => false);
  });

  test('housing-search-button: Search button visible', async ({ page }) => {
    await page.goto('/housing/search');
    await page.waitForTimeout(3000);
    const searchButton = page.locator('[data-testid="button-search"]');
    const buttonVisible = await searchButton.isVisible().catch(() => false);
  });

  test('housing-results-render: Result cards render', async ({ page }) => {
    await page.goto('/housing/search');
    await page.waitForTimeout(3000);
    const resultCards = page.locator('[data-testid^="card-result-"]');
    const count = await resultCards.count();
    expect(count).toBeGreaterThanOrEqual(0);
  });

});

test.describe('Housing Marketplace', () => {

  test('housing-marketplace-loads: Marketplace page loads', async ({ page }) => {
    await page.goto('/housing');
    await page.waitForTimeout(3000);
    await expect(page.locator('body')).toBeVisible();
  });

  test('housing-marketplace-heading: Marketplace heading visible', async ({ page }) => {
    await page.goto('/housing');
    await page.waitForTimeout(3000);
    const heading = page.locator('[data-testid="heading-housing-marketplace"]');
    const headingVisible = await heading.isVisible().catch(() => false);
  });

  test('housing-post-listing-button: Post listing button visible', async ({ page }) => {
    await page.goto('/housing');
    await page.waitForTimeout(3000);
    const postButton = page.locator('[data-testid="button-post-listing"]');
    const buttonVisible = await postButton.isVisible().catch(() => false);
  });

  test('housing-listing-cards: Listing cards render', async ({ page }) => {
    await page.goto('/housing');
    await page.waitForTimeout(3000);
    const listingCards = page.locator('[data-testid^="card-listing-"]');
    const count = await listingCards.count();
    expect(count).toBeGreaterThanOrEqual(0);
  });

});
