import { test, expect } from '@playwright/test';

/**
 * Direct Messages - Automated Tests
 * Generated by Mr. Blue Agent Test Orchestrator
 * Page: messages-page
 * 
 * Known Issues:
 * - WebSocket disconnect: Implement reconnection with exponential backoff
 * - message order wrong: Sort by createdAt timestamp descending
 */

test.describe('Direct Messages', () => {

  test('test-dm-list: DM conversations list loads', async ({ page }) => {
    // Expected: List of conversations visible
    await page.goto('/messages');
    await page.waitForTimeout(2000);
    const conversations = page.locator('[data-testid="conversations-list"]');
    const conversationsVisible = await conversations.isVisible().catch(() => false);
    // Page should load
    await expect(page.locator('body')).toBeVisible();
  });

  test('test-send-message: Sending a message works', async ({ page }) => {
    // Expected: Message appears in thread
    await page.goto('/messages');
    await page.waitForTimeout(2000);
    // Select first conversation if available
    const firstConvo = page.locator('[data-testid="conversation-item"]').first();
    if (await firstConvo.isVisible()) {
      await firstConvo.click();
      await page.waitForTimeout(1000);
      const messageInput = page.locator('[data-testid="message-input"]');
      if (await messageInput.isVisible()) {
        await messageInput.fill(`Test message ${Date.now()}`);
        await page.locator('[data-testid="send-button"]').click();
        await page.waitForTimeout(1000);
      }
    }
  });

  test('test-new-dm: Starting new conversation works', async ({ page }) => {
    // Expected: New thread created
    await page.goto('/messages');
    await page.waitForTimeout(2000);
    const newButton = page.locator('[data-testid="new-message-button"]');
    if (await newButton.isVisible()) {
      await newButton.click();
      await page.waitForTimeout(1000);
    }
  });

});
