export const HEAVY_FEATURES_ENABLED = import.meta.env.VITE_ENABLE_HEAVY_FEATURES === 'true';

export const ENABLE_3D_FEATURES = HEAVY_FEATURES_ENABLED;
export const ENABLE_VISUAL_EDITOR = HEAVY_FEATURES_ENABLED;
export const ENABLE_TRANSFORMERS = HEAVY_FEATURES_ENABLED;
export const ENABLE_PRISM = HEAVY_FEATURES_ENABLED;
export const ENABLE_RECHARTS = HEAVY_FEATURES_ENABLED;
