import { test, expect } from '@playwright/test';

/**
 * Events List - Automated Tests
 * Generated by Mr. Blue Agent Test Orchestrator
 * Page: events-page
 */

test.describe('Events List', () => {

  test('events-page-loads: Events page renders successfully', async ({ page }) => {
    await page.goto('/events');
    await page.waitForTimeout(3000);
    await expect(page.locator('body')).toBeVisible();
  });

  test('events-create-button: Create event button visible', async ({ page }) => {
    await page.goto('/events');
    await page.waitForTimeout(3000);
    const createButton = page.locator('[data-testid="button-create-event"]');
    const buttonVisible = await createButton.isVisible().catch(() => false);
  });

  test('events-search-input: Search input visible', async ({ page }) => {
    await page.goto('/events');
    await page.waitForTimeout(3000);
    const searchInput = page.locator('[data-testid="input-search-events"]');
    const inputVisible = await searchInput.isVisible().catch(() => false);
  });

  test('events-filter-button: Filter button visible', async ({ page }) => {
    await page.goto('/events');
    await page.waitForTimeout(3000);
    const filterButton = page.locator('[data-testid="button-open-filters"]');
    const buttonVisible = await filterButton.isVisible().catch(() => false);
  });

  test('events-view-tabs: View tabs available (list/calendar/map)', async ({ page }) => {
    await page.goto('/events');
    await page.waitForTimeout(3000);
    const listTab = page.locator('[data-testid="tab-list-view"]');
    const calendarTab = page.locator('[data-testid="tab-calendar-view"]');
    const mapTab = page.locator('[data-testid="tab-map-view"]');
    const listVisible = await listTab.isVisible().catch(() => false);
    const calendarVisible = await calendarTab.isVisible().catch(() => false);
    const mapVisible = await mapTab.isVisible().catch(() => false);
  });

  test('events-cards-render: Event cards render', async ({ page }) => {
    await page.goto('/events');
    await page.waitForTimeout(3000);
    const eventCards = page.locator('[data-testid^="card-event-"]');
    const count = await eventCards.count();
    expect(count).toBeGreaterThanOrEqual(0);
  });

  test('events-results-count: Results count displays', async ({ page }) => {
    await page.goto('/events');
    await page.waitForTimeout(3000);
    const resultsCount = page.locator('[data-testid="text-results-count"]');
    const countVisible = await resultsCount.isVisible().catch(() => false);
  });

});
