import { test, expect } from '@playwright/test';

/**
 * Event Creation - Automated Tests
 * Generated by Mr. Blue Agent Test Orchestrator
 * Page: events-page
 * 
 * Known Issues:
 * - date validation fail: Ensure date is in future before submission
 */

test.describe('Event Creation', () => {

  test('test-create-button: Create event button visible', async ({ page }) => {
    // Expected: Create button accessible
    await page.goto('/events');
    await page.waitForTimeout(2000);
    const createButton = page.locator('[data-testid="create-event-button"]');
    const createVisible = await createButton.isVisible().catch(() => false);
  });

  test('test-form-steps: Multi-step form navigates correctly', async ({ page }) => {
    // Expected: Steps progress forward/backward
    await page.goto('/events/create');
    await page.waitForTimeout(2000);
    const titleInput = page.locator('[data-testid="input-event-title"]');
    if (await titleInput.isVisible()) {
      await titleInput.fill('Test Milonga');
      const nextButton = page.locator('[data-testid="next-step-button"]');
      if (await nextButton.isVisible()) {
        await nextButton.click();
        await page.waitForTimeout(1000);
      }
    }
  });

  test('test-submit-event: Submitting creates event', async ({ page }) => {
    // Expected: Event created with success message
    await page.goto('/events/create');
    await page.waitForTimeout(2000);
    const titleInput = page.locator('[data-testid="input-event-title"]');
    if (await titleInput.isVisible()) {
      await titleInput.fill(`Test Event ${Date.now()}`);
      const submitButton = page.locator('[data-testid="submit-event-button"]');
      if (await submitButton.isVisible()) {
        await submitButton.click();
        await page.waitForTimeout(3000);
      }
    }
  });

});
