import { test, expect } from '@playwright/test';

/**
 * Admin Dashboard - Automated Tests
 * Generated by Mr. Blue Agent Test Orchestrator
 * Page: admin-page
 */

test.describe('Admin Dashboard', () => {

  test('admin-page-loads: Admin dashboard renders or redirects', async ({ page }) => {
    await page.goto('/admin');
    await page.waitForTimeout(3000);
    await expect(page.locator('body')).toBeVisible();
  });

  test('admin-dashboard-container: Dashboard container visible', async ({ page }) => {
    await page.goto('/admin');
    await page.waitForTimeout(3000);
    const dashboard = page.locator('[data-testid="page-admin-dashboard"]');
    const dashboardVisible = await dashboard.isVisible().catch(() => false);
  });

  test('admin-tabs: Admin tabs visible', async ({ page }) => {
    await page.goto('/admin');
    await page.waitForTimeout(3000);
    const tabs = page.locator('[data-testid="tabs-admin"]');
    const tabsVisible = await tabs.isVisible().catch(() => false);
  });

  test('admin-moderation-tab: Moderation tab available', async ({ page }) => {
    await page.goto('/admin');
    await page.waitForTimeout(3000);
    const moderationTab = page.locator('[data-testid="tab-moderation"]');
    const tabVisible = await moderationTab.isVisible().catch(() => false);
  });

  test('admin-analytics-tab: Analytics tab available', async ({ page }) => {
    await page.goto('/admin');
    await page.waitForTimeout(3000);
    const analyticsTab = page.locator('[data-testid="tab-analytics"]');
    const tabVisible = await analyticsTab.isVisible().catch(() => false);
  });

  test('admin-stat-cards: Stat cards render', async ({ page }) => {
    await page.goto('/admin');
    await page.waitForTimeout(3000);
    const statCards = page.locator('[data-testid^="stat-card-"]');
    const count = await statCards.count();
    expect(count).toBeGreaterThanOrEqual(0);
  });

});
